### ISSUE TITLE
Support for reading images as bytes in rten_imageio

### ISSUE THREAD

**Issue by remykarem** [robertknight/rten#39]
Hi, I think it would help a lot of we could have a utility for reading images as bytes in the `rten_imageio` crate.

Currently, there's only reading from the path `rten_imageio::read_image(path: &str)`.

**Comment by robertknight** [comment]
It would probably make sense to have a variant that accepts any type implementing `std::io::Read`, which includes `&[u8]`. This would then use [image::io::Reader](https://docs.rs/image/latest/image/io/struct.Reader.html#). In the meantime, I suggest you copy and paste the `read_image` implementation into your project and adjust as needed, since it is quite short.

**Comment by carlocorradini** [comment]
Any update? 🤯
This is super useful 🥳

**Comment by robertknight** [comment]
I haven't gotten around to this yet. My previous comment stands - copy and paste the `read_image` code from https://github.com/robertknight/rten/blob/665ea51d0ee80fed28fe249d484004e3e9571539/rten-imageio/src/lib.rs#L24 into your project, and change it to use [`image::load_from_memory`](https://docs.rs/image/latest/image/fn.load_from_memory.html) instead of `image::open`.

**Comment by robertknight** [comment]
In the context of Ocrs and its `OcrEngine::prepare_input` API, this problem has been solved by re-designing the API for loading images. See https://github.com/robertknight/ocrs/pull/56 and the updated examples for details.
